### ISSUE TITLE
Unable to configure

### ISSUE THREAD

**Issue by LordLinhey** [pbrunier/node-red-contrib-dyson-purelink#83]
After placing the Node and clicking the node, nothing happens, so you cannot configure it.
Also after doing this no other node that needs configuring works until you restart Node-red.

I have tried this with a Node-red test version on a linux machine v3.1.3 and on my regular Pi4 machine installed as an addon to Home assistant v17.0.9, and both are the same.

Can you help please?

Thanks

**Comment by pbrunier** [comment]
@LordLinhey Problem is fixed in 0.8.2. Please have some patience for it to appear in the NodeRED catalogue.

**Comment by acaranta** [comment]
Thx for the answer, however, I was wondering if you had any kind of ETA for the deployment of at least v0.8.2 ? 🤗 
I still isn't showing up in nodered catalog .. to be honest I have no idea what the process is 🙈 

BTW : Thx for your work, it is awesome and bloody useful :)

**Comment by acaranta** [comment]
(Sorry for the useless message I deleted :) )
But: I wanted to keep the part saying : Thx for your work, it is awesome :)

**Comment by pbrunier** [comment]
@acaranta Just forced the flows.nodered.org to update. It now reflects 0.8.4

**Comment by acaranta** [comment]
Thank you very much 🤗
